/*
This file is generated by https://github.com/nok/sklearn-porter/

Estimator:
    GaussianNB
    https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html

Environment:
    scikit-learn v0.22
    sklearn-porter v1.0.0

Usage:
    1. Execute a prediction:
        $ node GaussianNB.js feature_1 ... feature_5
*/
var GaussianNB = function(priors, sigmas, thetas) {

    this.priors = priors;
    this.sigmas = sigmas;
    this.thetas = thetas;

    var _findMax = function(nums) {
        var i = 0, l = nums.length, idx = 0;
        for (; i < l; i++) {
            idx = nums[i] > nums[idx] ? i : idx;
        }
        return idx;
    };

    var _logSumExp = function(nums) {
        var i, l = nums.length;
        var max = Math.max(...nums);
        var sum = 0.;
        for (i = 0; i < l; i++) {
            sum += Math.exp(nums[i] - max);
        }
        return max + Math.log(sum);
    };

    var _compute = function(features, priors, sigmas, thetas) {
        var i, il, j, jl, sum, nij,
            likelihoods = new Array(sigmas.length);
        for (i = 0, il = sigmas.length; i < il; i++) {
            sum = 0.;
            for (j = 0, jl = sigmas[0].length; j < jl; j++) {
                sum += Math.log(2. * Math.PI * sigmas[i][j]);
            }
            nij = -0.5 * sum;
            sum = 0.;
            for (j = 0, jl = sigmas[0].length; j < jl; j++) {
                sum += Math.pow(features[j] - thetas[i][j], 2.) / sigmas[i][j];
            }
            nij -= 0.5 * sum;
            likelihoods[i] = Math.log(priors[i]) + nij;
        }
        return likelihoods;
    };

    this.predict = function(features) {
        return _findMax(_compute(features, this.priors, this.sigmas, this.thetas));
    };

    this.predictProba = function(features) {
        var jll = _compute(features, this.priors, this.sigmas, this.thetas);
        var sum = _logSumExp(jll);
        for (i = 0; i < jll.length; i++) {
            jll[i] = Math.exp(jll[i] - sum);
        }
        return jll;
    };

};

var main = function () {
    if (typeof process !== 'undefined' && typeof process.argv !== 'undefined') {
        if (process.argv.length - 2 !== 5) {
            var IllegalArgumentException = function(message) {
                this.message = message;
                this.name = "IllegalArgumentException";
            }
            throw new IllegalArgumentException("You have to pass 5 features.");
        }
    }

    // Features:
    var features = process.argv.slice(2);
    for (var i = 0; i < features.length; i++) {
        features[i] = parseFloat(features[i]);
    }

    // Model data:
    var priors = [0.4939106901217862, 0.5060893098782138];
    var sigmas = [[209672.5458046464, 46273.3704997112, 4.629272464034061, 1916.1953599100862, 1520.0326276901556], [241136.3079324748, 46298.57549088368, 7.322438179891191, 81691.8801249882, 100694.46098231901]];
    var thetas = [[939.6821917808219, 355.7287671232877, 8.6, 36.26575342465753, 8.378082191780821], [787.7219251336899, 356.20588235294116, 9.109625668449198, 216.63101604278074, 254.2620320855615]];

    // Estimator:
    var clf = new GaussianNB(priors, sigmas, thetas);

    // Get class prediction:
    var prediction = clf.predict(features);
    console.log("Predicted class: #" + prediction);

    // Get class probabilities:
    var probabilities = clf.predictProba(features);
    for (var i = 0; i < probabilities.length; i++) {
        console.log("Probability of class #" + i + " : " + probabilities[i]);
    }
}

if (require.main === module) {
    main();
}