Alt = "KB_L_ALT"
AltGr = "KB_R_ALT"
Backspace = "KB_DELETE_BACKSPACE"
CapsLock = "KB_CAPS_LOCK"
ControlLeft = "KB_L_CTRL"
ControlRight = "KB_R_CTRL"
Delete = "KB_DELETE_FORWARD"
DownArrow = "KB_DOWN_ARROW"
End = "KB_END"
Escape = "KB_ESCAPE"
F1 = "KB_F1"
F10 = "KB_F10"
F11 = "KB_F11"
F12 = "KB_F12"
F2 = "KB_F2"
F3 = "KB_F3"
F4 = "KB_F4"
F5 = "KB_F5"
F6 = "KB_F6"
F7 = "KB_F7"
F8 = "KB_F8"
F9 = "KB_F9"
Home = "KB_HOME"
LeftArrow = "KB_LEFT_ARROW"
# also known as "windows", "super", and "command ”
MetaLeft = "KB_L_GUI"
# also known as "windows", "super", and "command"
MetaRight = "KB_R_GUI"
PageDown = "KB_PAGEDOWN"
PageUp = "KB_PAGEUP"
Return = "KB_ENTER"
RightArrow = "KB_RIGHT_ARROW"
ShiftLeft = "KB_L_SHIFT"
ShiftRight = "KB_R_SHIFT"
Space = "KB_SPACEBAR"
Tab = "KB_TAB"
UpArrow = "KB_UP_ARROW"
PrintScreen = "KB_PRINT_SCREEN"
ScrollLock = "KB_SCROLL_LOCK"
Pause = "KB_PAUSE"
NumLock = "KB_LOCKING_NUM_LOCK"
BackQuote = "KB_GRAVE_ACCENT_N_TILDE"
Num1 = "KB_1"
Num2 = "KB_2"
Num3 = "KB_3"
Num4 = "KB_4"
Num5 = "KB_5"
Num6 = "KB_6"
Num7 = "KB_7"
Num8 = "KB_8"
Num9 = "KB_9"
Num0 = "KB_0"
Minus = "KB_MINUS_N_UNDERSCORE"
Equal = "KB_EQUAL_N_PLUS"
KeyQ = "KB_Q"
KeyW = "KB_W"
KeyE = "KB_E"
KeyR = "KB_R"
KeyT = "KB_T"
KeyY = "KB_Y"
KeyU = "KB_U"
KeyI = "KB_I"
KeyO = "KB_O"
KeyP = "KB_P"
KeyA = "KB_A"
KeyS = "KB_S"
KeyD = "KB_D"
KeyF = "KB_F"
KeyG = "KB_G"
KeyH = "KB_H"
KeyJ = "KB_J"
KeyK = "KB_K"
KeyL = "KB_L"
KeyZ = "KB_Z"
KeyX = "KB_X"
KeyC = "KB_C"
KeyV = "KB_V"
KeyB = "KB_B"
KeyN = "KB_N"
KeyM = "KB_M"
LeftBracket = "KB_OPEN_BRACKET_N_BRANCE"
RightBracket = "KB_CLOSE_BRACKET_N_BRANCE"
SemiColon = "KB_SEMICOLON_N_COLON"
Quote = "KB_SINGLE_QUOTE_N_QUOTE"
BackSlash = "KB_BACK_SPLASH_N_VERTICAL_BAR"
IntlBackslash = ""
Comma = "KB_COMMA_N_LESS_THAN"
Dot = "KB_DOT_N_GREATER_THAN"
Slash = "KB_FORWARD_SPLASH_N_QUESTION_MARK"
Insert = "KB_INSERT"
KpReturn = "KP_ENTER"
KpMinus = "KP_MINUS"
KpPlus = "KP_PLUS"
KpMultiply = "KP_ASTERISK"
KpDivide = "KP_FORWARD_SPLASH"
Kp0 = "KP_0_N_INSERT"
Kp1 = "KP_1_N_END"
Kp2 = "KP_2_N_DOWN_ARROW"
Kp3 = "KP_3_N_PAGEDN"
Kp4 = "KP_4_N_LEFT_ARROW"
Kp5 = "KP_5"
Kp6 = "KP_6_N_RIGHT_ARROW"
Kp7 = "KP_7_N_HOME"
Kp8 = "KP_8_N_UP_ARROW"
Kp9 = "KP_9_N_PAGEUP"
KpDelete = "KP_DOT_N_DELETE"
Function = ""